### ISSUE TITLE
Expand notification to all available width

### ISSUE THREAD

**Issue by Thunderforge** [atlassian-labs/atlassian-slack-integration-server#123]
If you expand Slack to take the full length of a widescreen monitor, you will see that notifications only take up a fraction of the screen real estate.

<img width="1381" alt="Bitbucket notification" src="https://user-images.githubusercontent.com/6200170/125640184-a597ac54-b6da-4a48-b1e8-ed76de233d99.png">

I would like to request that it takes *all* available screen width and only wrapping onto the next line if there isn't enough, rather than being artificially constrained.

**Comment by utluiz** [comment]
Hey!

Thanks for the feedback. However, this is a Slack limitation, at least when rendering certain messages formatted and sent by bots. AFAICT there's no workaround, thus this feedback would be more appropriately addressed to Slack.

I will close this issue for now. It can be reopened a solution for this issue arises from the Slack side.
