### ISSUE TITLE
When changing custom field while transitioning a ticket wrong value is put to the index

### ISSUE THREAD

**Issue by nwroblewska** [atlassian-labs/atlassian-slack-integration-server#133]
Issue Summary
Changes done to the ticket are not reflected in the index - JQL query. 

For example: There is a Select List (single choice) custom field “xyz”. When there are changes to it, they are reflected in the issue details screen but not in the JQL query result.

The problem cannot be reproduced every time.

Steps to Reproduce
Transition an issue within the project which uses slack integration and updates a Select List (single choice)  field with a new value.
Search issue against the custom field.
 key =xyz-1234 and cf[10000] is not empty 
 

Expected Results
The value and the details screen and in the JQL search are the same every time.

Actual Results
The value on the details screen is correct. The JQL search shows the wrong value. 

Workaround
Currently, there is no known workaround for this behaviour. A workaround will be added here when available

**Comment by Diana520** [comment]
I tried to reproduce the issue but I failed to do that. Most probably this fix was included into 2.0.16 version. If you faced the same issue please try to update to 2.0.16 version or later.
