### ISSUE TITLE
Prevent unnecessary reindex on JQL matching when sending a subscription notification

### ISSUE THREAD

**Issue by utluiz** [atlassian-labs/atlassian-slack-integration-server#136]
~We have the information that Jira 8 has fixed data inconsistencies when firing issue events so cording the reindex of the issue would not be necessary.~

~Forced reindex has a big performance penalty and a big boost could come out of removing it.~

~Forcing issue reindex is a historical pattern that this integration has followed and may not be necessary anymore. However, given this is a sensitive feature (susceptible to concurrency problems that may lead to missing notifications and inconsistent behavior), we have to take into account the risk of introducing such a change for existing customers.~

~So I suggest we add a system property to switch forced reindex on and off. Customers using newer versions of Jira can turn forced reindex off and thus get the performance boost. Customers that notice missing notifications can keep it on.~

See comment below.

**Comment by mvlasovatl** [comment]
The improvement was implemented in #195 and merged to `dev`. It will be included into next release.

**Comment by mvlasovatl** [comment]
The fix was included into Jira Server for Slack 3.0.1.
