### ISSUE TITLE
Remove usage of deprecated Task API

### ISSUE THREAD

**Issue by mgoyal2-atl** [atlassian-labs/atlassian-slack-integration-server#180]
Bitbucket integration plugin uses deprecated API from [com.atlassian.bitbucket.task package](https://docs.atlassian.com/bitbucket-server/javadoc/7.21.0/api/com/atlassian/bitbucket/task/package-summary.html) which will be removed in Bitbucket 8.0

The goal of this issue is to replace this API usage with appropriate API that will be available in Bitbucket 8.0

**Comment by mvlasovatl** [comment]
The fix was implemented in #179 and included into Bitbucket Server for Slack v.4.0.1.
