### ISSUE TITLE
Validate plugin for upcoming Jira 9 Major Release

### ISSUE THREAD

**Issue by knoppanthony** [atlassian-labs/atlassian-slack-integration-server#185]
EAP is here https://www.atlassian.com/software/jira/download-eap?_ga=2.227824606.291373623.1647880020-2043599991.1647029962

Looking for a smoke test to ensure plugin is still compatible. No known big backwards breaking changes.

**Comment by knoppanthony** [comment]
cc: @mvlasovatl

**Comment by mvlasovatl** [comment]
I am looking at it at the moment. Here is the full list of Jira 9 changes: https://confluence.atlassian.com/jiracore/preparing-for-jira-9-0-1115661092.html .

**Comment by mvlasovatl** [comment]
Compatibility with Jira 9 was implemented in #187 and included into Jira Server for Slack 3.0.0.
