### ISSUE TITLE
Text spacing issue in Slack view oauth sessions

### ISSUE THREAD

**Issue by atl-lbernardo** [atlassian-labs/atlassian-slack-integration-server#211]
#### Why?

Found via https://jira.atlassian.com/browse/JSDSERVER-11885

Looks like a papercut fix in the properties file
https://github.com/atlassian-labs/atlassian-slack-integration-server/blob/master/slack-server-integration-common/src/main/resources/com/atlassian/plugins/slack/slack-common.properties#L134

**Comment by atl-lbernardo** [comment]
hi @mvlasovatl i have a branch and fix ready id like to push to create a PR, do i have to be a contributor to do this? thanks

**Comment by mvlasovatl** [comment]
The fix is merged to `dev` now. It will be included into next release of each of the plugins.

**Comment by mvlasovatl** [comment]
The fix was included into the following releases:
- Jira Server for Slack 3.0.4
- Confluence Server for Slack 3.0.1
- Bitbucket Server for Slack 4.0.5
