### ISSUE TITLE
can this integration support create issues from slack as the cloud version do

### ISSUE THREAD

**Issue by yunyu950908** [atlassian-labs/atlassian-slack-integration-server#244]
can this integration support create issues from slack as the cloud version do?

like these message shortcuts
<img width="296" alt="image" src="https://user-images.githubusercontent.com/25625252/204548124-6f68afb1-c3aa-4149-80fe-c381972fb2d5.png">
<img width="532" alt="image" src="https://user-images.githubusercontent.com/25625252/204548490-6e42ce75-4429-4cb8-ad75-9ce52e247a33.png">

**Comment by mvlasovatl** [comment]
Hey @yunyu950908 ! Server product Slack plugins are in maintenance mode now. We are not adding new features, just fix some critical bugs and vulnerabilities and keep the plugins compatible with newest product versions.
If you want to have this feature, feel free to fork the repo and implement it within your team. Contributions are welcome as well!

**Comment by mvlasovatl** [comment]
Closing this one as answered.
