### ISSUE TITLE
[Confluence] Pages with deleted creators cannot receive any new comments or checkbox checks

### ISSUE THREAD

**Issue by tosts** [atlassian-labs/atlassian-slack-integration-server#33]
https://github.com/atlassian-labs/atlassian-slack-integration-server/blob/1a4b4465891cd7835ff6b9f528f320a47298b231/confluence-slack-server-integration-plugin/src/main/java/com/atlassian/confluence/plugins/slack/spacetochannel/service/PersonalNotificationService.java#L77

If the creator of the parent page has been deleted in the mean time, he is then asked for his user_key in this function call.
The subsequent slackUserSettingsService call, to check on his notification settings, will throw an IllegalArgumentException.
This kills the calling EventHandler and forces a rollback on the underlying DB transaction.

This prevents comments from being created or checkboxes on the page to be checked.

**Comment by robertoschwald** [comment]
https://jira.atlassian.com/browse/CONFSERVER-59108

**Comment by mvlasovatl** [comment]
This issue was tackled in #172 that was merged to `dev`. It is pending next release now.

**Comment by mvlasovatl** [comment]
Confluence Server for Slack 2.1.4.
