### ISSUE TITLE
Massive number of personal notifications about "re-scoping" PRs

### ISSUE THREAD

**Issue by yan-uvarovsky** [atlassian-labs/atlassian-slack-integration-server#344]
After upgrading plugin version from 4.0.8 to 4.0.9 developers started to receive a lot of personal notifications in Slack for "pull  request re-scoped" events.
It looks like that every commit to repository triggers something called "[re-scope](https://confluence.atlassian.com/bitbucketserverkb/how-to-diagnose-debug-issues-with-pull-request-rescoping-in-bitbucket-data-center-1026057670.html)" of each PR in BitBucket Server and every such event leads to a separate notification. If you have 30 PRs open for a given repo each developer will receive 30 Slack notifications for every push to this repository:
![image](https://github.com/atlassian-labs/atlassian-slack-integration-server/assets/159151154/72dfe42a-474b-4774-9585-00c6fdd11edc)

There is no dedicated toggle for this event in BitBucket UI:
![image](https://github.com/atlassian-labs/atlassian-slack-integration-server/assets/159151154/1627e246-4239-46c6-b9ef-4e4ae4b7e68a)

We had to roll back to 4.0.8.
We use Atlassian Bitbucket v7.21.21

**Comment by mvlasovatl** [comment]
Oh it must be caused by #277 . Please roll back to 4.0.8 while we are working on fix.

**Comment by YevhenHrytsai** [comment]
Version `4.0.10` with a fix to this issue is available on the Marketplace
[Bitbucket Data Center for Slack](https://marketplace.atlassian.com/apps/1220729/bitbucket-data-center-for-slack-official?tab=versions&hosting=datacenter)
