### ISSUE TITLE
Commenting on issues, adding content to issues?

### ISSUE THREAD

**Issue by jcam** [atlassian-labs/atlassian-slack-integration-server#41]
It appears that the cloud app has a lot more support for interacting with Jira from slack.
Is this additional functionality in the works for DataCenter?

Thanks!

**Comment by sethgho** [comment]
Hi @jcam - I've just updated the README with our expectations for continued feature development. 

> In order to [accelerate our journey to the cloud, together](https://www.atlassian.com/blog/announcements/journey-to-cloud), Atlassian will continue to maintain these apps' compatibility with our Server products. However, we will not be creating new features or matching feature parity with our Cloud integrations. If you would like to add your own customizations/features to the integration, we encourage you to fork this repository and customize it as you wish like we’ve seen many customers do.
>
> When Jira, Confluence, or Bitbucket Server release new versions, we will validate the compatibility of these apps and release new versions within four weeks of their public release.

**Comment by jcam** [comment]
The link you provided, "accelerate our journey to the cloud" does not mention ending support for Data Center at all, so I'm not sure how that applies?
