### ISSUE TITLE
Personal notifications are sent to not all interested users

### ISSUE THREAD

**Issue by mvlasovatl** [atlassian-labs/atlassian-slack-integration-server#48]
Steps:
1. Watch the issue ISS-1 as USER1 and as USER2.
2. Set up personal notifications for both USER1 and USER2.
3. As user USER3 make some changes to issue ISS-1.

Expected: both watchers with personal notifications configured receive a notification about the change.
Actual: just one watcher receives a notification.

**Comment by 3ric-Design** [comment]
If someone watch an issue, the assignee don't get a notification too.
The problem isn't only the watcher. If more then 1 person of an issue want to get notification we get this very high problem. :(

**Comment by mvlasovatl** [comment]
Fixed in #53.

**Comment by 3ric-Design** [comment]
Wow, that was fast, thanks a lot! :)
