### ISSUE TITLE
Request: Make Slack Message about Ticket Public

### ISSUE THREAD

**Issue by Christopher-Hayes** [atlassian-labs/atlassian-slack-integration-server#96]
Right now doing /jira_server XYZ-1234 only shows you info about a ticket. Is there a way to show it to everyone in a channel / DM instead or could this feature be added?

**Comment by mvlasovatl** [comment]
Hello Christopher! The app provides 2 ways to get issue details by its key: using slash command you mentioned (generates private preview) and by sending an issue key to a channel with active subscription and Jira bot user present (generates public issue preview).

**Comment by Christopher-Hayes** [comment]
Ah okay, I see. I was trying to use it in a DM.
